# Generated by Django 3.2.16 on 2022-11-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0006_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music',
            field=models.FileField(blank=True, upload_to='music/'),
        ),
    ]
