# Generated by Django 3.2.16 on 2022-11-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0008_alter_post_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music_title',
            field=models.CharField(default='music_title', max_length=50, verbose_name='曲名'),
        ),
    ]
