# Generated by Django 3.2.16 on 2022-11-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0010_alter_post_music_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_url',
            field=models.TextField(default=1, max_length=100, verbose_name='YouTubeのURL'),
            preserve_default=False,
        ),
    ]
