# Generated by Django 3.2.16 on 2022-11-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0013_alter_post_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='タイトル'),
        ),
    ]
