# Generated by Django 3.2.16 on 2022-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0015_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='内容'),
        ),
    ]
