# Generated by Django 3.2.16 on 2022-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0016_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='music_title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='曲名'),
        ),
    ]
