# Generated by Django 3.2.16 on 2022-11-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0019_alter_post_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='アーティスト名'),
        ),
    ]
