# Generated by Django 3.2.16 on 2022-11-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0023_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pmapp.genre'),
        ),
    ]
