# Generated by Django 3.2.16 on 2022-11-27 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0035_auto_20221128_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pmapp.post', verbose_name='対象記事'),
            preserve_default=False,
        ),
    ]
