# Generated by Django 3.2.16 on 2022-11-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0036_comment_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=1, max_length=1000, verbose_name='内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=30, verbose_name='YouTubeのURL'),
        ),
    ]
