# Generated by Django 3.2.16 on 2022-11-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0037_auto_20221130_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post_pk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_id', to='pmapp.post', verbose_name='投稿ID'),
            preserve_default=False,
        ),
    ]
