# Generated by Django 3.2.16 on 2022-12-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0040_post_date_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music_phrase',
            field=models.TextField(blank=True, max_length=15, verbose_name='曲ワンフレーズ'),
        ),
    ]
