# Generated by Django 3.2.16 on 2022-12-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0041_post_music_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='music_phrase',
            field=models.CharField(blank=True, max_length=15, verbose_name='歌詞ワンフレーズ'),
        ),
    ]
