# Generated by Django 3.2.16 on 2022-12-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0042_alter_post_music_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
